### PR TITLE
yrkrta

### PR DESCRIPTION
**Pull request by estifanoskbrabe**
In our second project we have used two main concepts in java the interface and decorator . An interface is like a blueprint for class defining the methods they should have without specifying how they should be implemented. In our project our Interface is the namable interface which behaves like a class but it does not specify any object. The other is the decorator .Decorator is a design pattern that allows you to dynamically add functionality to an object at runtime by wrapping it with another object that has the same interface. we have used two specific types of decorator the trimmer and capitalize.

### CODE REVIEW

**Review by Benawi — CHANGES_REQUESTED** [review]
Hi 👋 @estifanoskbrabe 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

  - Person, Teacher, and student classes are empty in this branch
 
giphy

Your Code Review Request will be marked as invalid, so please submit a new one once you are ready 🙏


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Benawi — CHANGES_REQUESTED** [review]
Hi 👋 @estifanoskbrabe 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Person class deleted


giphy

Your Code Review Request will be marked as invalid, so please submit a new one once you are ready 🙏


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Benawi — APPROVED** [review]
Hi, @estifanoskbrabe 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
✅ Correct use of Gitflow
✅ Create a class ` Nameable` --- Interface
✅ `Person ` class inherits from `Nameable`
✅ Create `Decorator ` and inherits from `Nameable`.
✅ Create ` CapitalizeDecorator ` and ` TrimmerDecorator`


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @benawi in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by estifanoskbrabe** [comment]
Mr.habtamu I am receving email messages that are not mine

**Pull request merged**
